[package]
name = "EdgeAI"
version = "0.3.1"

[properties]

[[app]]
name = "EdgeAI"
main = "./src/RTAudioClassification.lf"
target = "Python"
platform = "Native"


[lib]
name = "EdgeAI"
location = "./src/"
target = "Python"
platform = "Native"

[lib.properties]
artifacts = [
    "./models/"
]

[dependencies]